/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRAMES;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dell
 */
public class Hostel_Admission_SystemFrame extends javax.swing.JFrame {

    /**
     * Creates new form Admission_System
     */
    public Hostel_Admission_SystemFrame() {
        initComponents();
         java.awt.Toolkit kit=this.getToolkit();
        java.awt.Dimension d=kit.getScreenSize();
        this.setBounds(0,0,d.width,d.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        facultyButton = new javax.swing.JButton();
        departmentButton = new javax.swing.JButton();
        programButton = new javax.swing.JButton();
        batchButton = new javax.swing.JButton();
        studentButton = new javax.swing.JButton();
        hosteButton = new javax.swing.JButton();
        partButton1 = new javax.swing.JButton();
        studPartButton1 = new javax.swing.JButton();
        hosteButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setTitle("UniversityOf Sindh");
        setBackground(new java.awt.Color(0, 0, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("HOSTEL  MANAGEMENT  SYSTEM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 730, -1));

        exitButton.setBackground(new java.awt.Color(255, 0, 0));
        exitButton.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 51));
        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 730, 200, 70));

        facultyButton.setBackground(new java.awt.Color(255, 255, 51));
        facultyButton.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        facultyButton.setText("FACULTY");
        facultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(facultyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 280, 50));

        departmentButton.setBackground(new java.awt.Color(255, 255, 51));
        departmentButton.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        departmentButton.setText("DEPARTMENT");
        departmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(departmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 280, 50));

        programButton.setBackground(new java.awt.Color(255, 255, 51));
        programButton.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        programButton.setText("PROGRAM");
        programButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programButtonActionPerformed(evt);
            }
        });
        getContentPane().add(programButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 280, 50));

        batchButton.setBackground(new java.awt.Color(255, 255, 51));
        batchButton.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        batchButton.setText("BATCH");
        batchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(batchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 280, 50));

        studentButton.setBackground(new java.awt.Color(255, 255, 51));
        studentButton.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        studentButton.setText("STUDENT");
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(studentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 280, 50));

        hosteButton.setBackground(new java.awt.Color(255, 255, 51));
        hosteButton.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        hosteButton.setText("ALLOTEMENT HOSTEL");
        hosteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hosteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hosteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 640, 280, 50));

        partButton1.setBackground(new java.awt.Color(255, 255, 51));
        partButton1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        partButton1.setText("PART");
        partButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(partButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 280, 50));

        studPartButton1.setBackground(new java.awt.Color(255, 255, 51));
        studPartButton1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        studPartButton1.setText("STUDPART");
        studPartButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studPartButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(studPartButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 280, 50));

        hosteButton1.setBackground(new java.awt.Color(255, 255, 51));
        hosteButton1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        hosteButton1.setText("HOSTEL");
        hosteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hosteButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(hosteButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 280, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\JAVA_Programs_A_To_Z\\DataBase\\Brick-House-Hostel-1200x800_c.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 920));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void facultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyButtonActionPerformed
        // TODO add your handling code here:
          FacultyFrame ob= null;
        try {
            ob = new FacultyFrame();
        } catch (Exception ex) {
            Logger.getLogger(Hostel_Admission_SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        ob.show();
    }//GEN-LAST:event_facultyButtonActionPerformed

    private void departmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentButtonActionPerformed
        // TODO add your handling code here:
        DepartmentFrame ob=new DepartmentFrame();
        ob.show();
    }//GEN-LAST:event_departmentButtonActionPerformed

    private void programButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programButtonActionPerformed
        // TODO add your handling code here:
           ProgramFrame ob=new ProgramFrame();
        ob.show();
    }//GEN-LAST:event_programButtonActionPerformed

    private void batchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchButtonActionPerformed
        // TODO add your handling code here:
         BatchFrame ob=new BatchFrame();
        ob.show();
    }//GEN-LAST:event_batchButtonActionPerformed

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        // TODO add your handling code here:
         StudentFrame ob=new StudentFrame();
        ob.show();
    }//GEN-LAST:event_studentButtonActionPerformed

    private void hosteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hosteButtonActionPerformed
        // TODO add your handling code here:
       Hostel_Allotement_Frame ob;
        try {
            ob = new Hostel_Allotement_Frame();
          ob.show();
        } catch (Exception ex) {
            Logger.getLogger(Hostel_Admission_SystemFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_hosteButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void partButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partButton1ActionPerformed
        // TODO add your handling code here:
        PartFrame ob=new PartFrame();
        ob.show();
    }//GEN-LAST:event_partButton1ActionPerformed

    private void studPartButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studPartButton1ActionPerformed
        // TODO add your handling code here:
        Students_Part_Frame ob=new Students_Part_Frame();
        ob.show();
    }//GEN-LAST:event_studPartButton1ActionPerformed

    private void hosteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hosteButton1ActionPerformed
        // TODO add your handling code here:
        
        HostelFrame ob=new HostelFrame();
        ob.show();
    }//GEN-LAST:event_hosteButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hostel_Admission_SystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hostel_Admission_SystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hostel_Admission_SystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hostel_Admission_SystemFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hostel_Admission_SystemFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batchButton;
    private javax.swing.JButton departmentButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton facultyButton;
    private javax.swing.JButton hosteButton;
    private javax.swing.JButton hosteButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton partButton1;
    private javax.swing.JButton programButton;
    private javax.swing.JButton studPartButton1;
    private javax.swing.JButton studentButton;
    // End of variables declaration//GEN-END:variables
}
